
import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "english" | "tamil" | "telugu" | "hindi" | "kannada";

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation keys
const translations: Record<Language, Record<string, string>> = {
  english: {
    dashboard: "Dashboard",
    production: "Production",
    inventory: "Inventory",
    quality: "Quality",
    finance: "Finance",
    hr: "Human Resources",
    crm: "Customer Relations",
    settings: "Settings",
    language: "Language",
    welcome: "Welcome to SpinWise ERP",
    overview: "System Overview",
    pendingOrders: "Pending Orders",
    stockStatus: "Stock Status",
    qualityMetrics: "Quality Metrics",
    recentTransactions: "Recent Transactions",
    employeePerformance: "Employee Performance",
    customerOrders: "Customer Orders",
    rawMaterials: "Raw Materials",
    workInProgress: "Work in Progress",
    finishedGoods: "Finished Goods",
    chat: "Chat with Assistant",
    chatPlaceholder: "Ask about yarn, machines, or procedures...",
    logout: "Logout",
    // Production translations
    running_machines: "Running Machines",
    issues: "Issues",
    avg_efficiency: "Average Efficiency",
    daily_production: "Daily Production",
    of_total: "of total",
    warnings: "warnings",
    errors: "errors",
    from_yesterday: "from yesterday",
    production_metrics: "Production Metrics",
    last_24_hours: "Last 24 Hours",
    quality_indicators: "Quality Indicators",
    current_shift: "Current Shift",
    yarn_strength: "Yarn Strength",
    yarn_evenness: "Yarn Evenness",
    imperfections: "Imperfections",
    waste_percentage: "Waste Percentage",
    good: "Good",
    average: "Average",
    poor: "Poor",
    machine_status: "Machine Status",
    production_kg: "Production (kg)",
    quality_percent: "Quality (%)",
    efficiency_percent: "Efficiency (%)",
    production_management: "Production Management",
    production_overview_description: "Monitor and manage spinning mill production processes",
    add_machine: "Add Machine",
    machines: "Machines",
    process_flow: "Process Flow",
    // Quality translations
    quality_management: "Quality Management",
    quality_overview_description: "Monitor and analyze yarn quality parameters",
    real_time_analysis: "Real-time Analysis",
    quality_trends: "Quality Trends",
    quality_alerts: "Quality Alerts",
    yarn_parameters: "Yarn Parameters",
    add_test: "Add Test",
    test_results: "Test Results",
    parameters: "Parameters",
    twist: "Twist",
    evenness: "Evenness",
    tensile_strength: "Tensile Strength",
    elongation: "Elongation",
    hairiness: "Hairiness",
    last_7_days: "Last 7 Days",
    deviation_detected: "Deviation Detected",
    critical_alert: "Critical Alert",
    warning_alert: "Warning Alert",
    info_alert: "Information",
    quality_forecast: "Quality Forecast",
    recommendations: "Recommendations",
    corrective_actions: "Corrective Actions",
    sensor_data: "Sensor Data",
    vision_systems: "Vision Systems",
    machine_learning: "Machine Learning",
    predicted_issues: "Predicted Issues",
    compliance: "Compliance",
    standards: "Standards",
    // Inventory translations
    inventory_management: "Inventory Management",
    inventory_overview_description: "Track and manage spinning mill inventory",
    raw_materials: "Raw Materials",
    work_in_progress: "Work in Progress",
    finished_goods: "Finished Goods",
    inventory_analytics: "Inventory Analytics",
    scan_barcode: "Scan Barcode",
    add_item: "Add Item",
    item_name: "Item Name",
    item_code: "Item Code",
    category: "Category",
    quantity: "Quantity",
    unit: "Unit",
    location: "Location",
    status: "Status",
    last_updated: "Last Updated",
    reorder_level: "Reorder Level",
    reorder_alerts: "Reorder Alerts",
    low_stock: "Low Stock",
    out_of_stock: "Out of Stock",
    expiring_soon: "Expiring Soon",
    days_until_reorder: "Days Until Reorder",
    inventory_value: "Inventory Value",
    turnover_rate: "Turnover Rate",
    wastage: "Wastage",
    in_stock: "In Stock",
    cotton: "Cotton",
    polyester: "Polyester",
    viscose: "Viscose",
    yarn_packages: "Yarn Packages",
    tons: "Tons",
    kilograms: "Kilograms",
    units: "Units",
  },
  tamil: {
    dashboard: "டாஷ்போர்டு",
    production: "உற்பத்தி",
    inventory: "சரக்கு",
    quality: "தரம்",
    finance: "நிதி",
    hr: "மனித வளம்",
    crm: "வாடிக்கையாளர் உறவுகள்",
    settings: "அமைப்புகள்",
    language: "மொழி",
    welcome: "ஸ்பின்வைஸ் ERP க்கு வரவேற்கிறோம்",
    overview: "அமைப்பு கண்ணோட்டம்",
    pendingOrders: "நிலுவையில் உள்ள ஆர்டர்கள்",
    stockStatus: "சரக்கு நிலை",
    qualityMetrics: "தர அளவீடுகள்",
    recentTransactions: "சமீபத்திய பரிவர்த்தனைகள்",
    employeePerformance: "ஊழியர் செயல்திறன்",
    customerOrders: "வாடிக்கையாளர் ஆர்டர்கள்",
    rawMaterials: "மூலப்பொருட்கள்",
    workInProgress: "முன்னேற்றத்தில் உள்ள வேலை",
    finishedGoods: "முடிக்கப்பட்ட பொருட்கள்",
    chat: "உதவியாளருடன் அரட்டை",
    chatPlaceholder: "நூல், இயந்திரங்கள் அல்லது நடைமுறைகள் பற்றி கேளுங்கள்...",
    logout: "வெளியேறு",
    // Production translations
    running_machines: "இயங்கும் இயந்திரங்கள்",
    issues: "சிக்கல்கள்",
    avg_efficiency: "சராசரி செயல்திறன்",
    daily_production: "தினசரி உற்பத்தி",
    of_total: "மொத்தத்தில்",
    warnings: "எச்சரிக்கைகள்",
    errors: "பிழைகள்",
    from_yesterday: "நேற்றிலிருந்து",
    production_metrics: "உற்பத்தி அளவீடுகள்",
    last_24_hours: "கடைசி 24 மணிநேரம்",
    quality_indicators: "தர குறிகாட்டிகள்",
    current_shift: "தற்போதைய ஷிஃப்ட்",
    yarn_strength: "நூல் வலிமை",
    yarn_evenness: "நூல் சமநிலை",
    imperfections: "குறைபாடுகள்",
    waste_percentage: "கழிவு சதவீதம்",
    good: "நல்லது",
    average: "சராசரி",
    poor: "மோசமான",
    machine_status: "இயந்திர நிலை",
    production_kg: "உற்பத்தி (கிலோ)",
    quality_percent: "தரம் (%)",
    efficiency_percent: "செயல்திறன் (%)",
    production_management: "உற்பத்தி மேலாண்மை",
    production_overview_description: "நூற்பாலை உற்பத்தி செயல்முறைகளை கண்காணித்து நிர்வகிக்கவும்",
    add_machine: "இயந்திரம் சேர்க்க",
    machines: "இயந்திரங்கள்",
    process_flow: "செயல்முறை ஓட்டம்",
    // Quality translations
    quality_management: "தர மேலாண்மை",
    quality_overview_description: "நூல் தர அளவுருக்களை கண்காணித்து பகுப்பாய்வு செய்யவும்",
    real_time_analysis: "நிகழ்நேர பகுப்பாய்வு",
    quality_trends: "தர போக்குகள்",
    quality_alerts: "தர எச்சரிக்கைகள்",
    yarn_parameters: "நூல் அளவுருக்கள்",
    add_test: "சோதனை சேர்க்க",
    test_results: "சோதனை முடிவுகள்",
    parameters: "அளவுருக்கள்",
    twist: "திருகு",
    evenness: "சமச்சீர்",
    tensile_strength: "இழுவிசை வலிமை",
    elongation: "நீட்சி",
    hairiness: "முடி போன்ற தன்மை",
    last_7_days: "கடந்த 7 நாட்கள்",
    deviation_detected: "விலகல் கண்டறியப்பட்டது",
    critical_alert: "முக்கியமான எச்சரிக்கை",
    warning_alert: "எச்சரிக்கை",
    info_alert: "தகவல்",
    quality_forecast: "தர முன்கணிப்பு",
    recommendations: "பரிந்துரைகள்",
    corrective_actions: "திருத்த நடவடிக்கைகள்",
    sensor_data: "உணர்வி தரவு",
    vision_systems: "காட்சி அமைப்புகள்",
    machine_learning: "இயந்திர கற்றல்",
    predicted_issues: "முன்கணிக்கப்பட்ட சிக்கல்கள்",
    compliance: "இணக்கம்",
    standards: "தரநிலைகள்",
    // Inventory translations
    inventory_management: "சரக்கு மேலாண்மை",
    inventory_overview_description: "நூற்பாலை சரக்குகளை கண்காணித்து நிர்வகிக்கவும்",
    raw_materials: "மூலப்பொருட்கள்",
    work_in_progress: "முன்னேற்றத்தில் உள்ள வேலை",
    finished_goods: "முடிக்கப்பட்ட பொருட்கள்",
    inventory_analytics: "சரக்கு பகுப்பாய்வு",
    scan_barcode: "பார்கோடை ஸ்கேன் செய்க",
    add_item: "பொருள் சேர்க்க",
    item_name: "பொருள் பெயர்",
    item_code: "பொருள் குறியீடு",
    category: "வகை",
    quantity: "அளவு",
    unit: "அலகு",
    location: "இடம்",
    status: "நிலை",
    last_updated: "கடைசியாக புதுப்பிக்கப்பட்டது",
    reorder_level: "மறுவரிசை நிலை",
    reorder_alerts: "மறுவரிசை எச்சரிக்கைகள்",
    low_stock: "குறைந்த சரக்கு",
    out_of_stock: "கைவசமில்லை",
    expiring_soon: "விரைவில் காலாவதியாகிறது",
    days_until_reorder: "மறுவரிசைக்கு முன் நாட்கள்",
    inventory_value: "சரக்கு மதிப்பு",
    turnover_rate: "சரக்கு சுழற்சி விகிதம்",
    wastage: "வீணாதல்",
    in_stock: "கையிருப்பில்",
    cotton: "பருத்தி",
    polyester: "பாலியெஸ்டர்",
    viscose: "விஸ்கோஸ்",
    yarn_packages: "நூல் பாக்கேஜ்கள்",
    tons: "டன்கள்",
    kilograms: "கிலோகிராம்",
    units: "அலகுகள்",
  },
  telugu: {
    dashboard: "డాష్‌బోర్డ్",
    production: "ఉత్పత్తి",
    inventory: "జాబితా",
    quality: "నాణ్యత",
    finance: "ఆర్థిక",
    hr: "మానవ వనరులు",
    crm: "వినియోగదారు సంబంధాలు",
    settings: "సెట్టింగ్‌లు",
    language: "భాష",
    welcome: "SpinWise ERP కు స్వాగతం",
    overview: "సిస్టమ్ అవలోకనం",
    pendingOrders: "పెండింగ్ ఆర్డర్‌లు",
    stockStatus: "స్టాక్ స్థితి",
    qualityMetrics: "నాణ్యత మెట్రిక్స్",
    recentTransactions: "ఇటీవలి లావాదేవీలు",
    employeePerformance: "ఉద్యోగి పనితీరు",
    customerOrders: "కస్టమర్ ఆర్డర్‌లు",
    rawMaterials: "ముడి పదార్థాలు",
    workInProgress: "పని జరుగుతోంది",
    finishedGoods: "పూర్తయిన వస్తువులు",
    chat: "సహాయకుడితో చాట్ చేయండి",
    chatPlaceholder: "దారం, యంత్రాలు లేదా విధానాల గురించి అడగండి...",
    logout: "లాగ్అవుట్",
    // Production translations
    running_machines: "నడుస్తున్న యంత్రాలు",
    issues: "సమస్యలు",
    avg_efficiency: "సగటు సామర్థ్యం",
    daily_production: "రోజువారీ ఉత్పత్తి",
    of_total: "మొత్తంలో",
    warnings: "హెచ్చరికలు",
    errors: "లోపాలు",
    from_yesterday: "నిన్న నుండి",
    production_metrics: "ఉత్పత్తి కొలమానాలు",
    last_24_hours: "గత 24 గంటలు",
    quality_indicators: "నాణ్యత సూచికలు",
    current_shift: "ప్రస్తుత షిఫ్ట్",
    yarn_strength: "దారం బలం",
    yarn_evenness: "దారం సమత్వం",
    imperfections: "లోపాలు",
    waste_percentage: "వ్యర్థ శాతం",
    good: "మంచిది",
    average: "సగటు",
    poor: "తక్కువ",
    machine_status: "యంత్రం స్థితి",
    production_kg: "ఉత్పత్తి (కిలోలు)",
    quality_percent: "నాణ్యత (%)",
    efficiency_percent: "సామర్థ్యం (%)",
    production_management: "ఉత్పత్తి నిర్వహణ",
    production_overview_description: "స్పిన్నింగ్ మిల్ ఉత్పత్తి ప్రక్రియలను పర్యవేక్షించండి మరియు నిర్వహించండి",
    add_machine: "యంత్రాన్ని జోడించండి",
    machines: "యంత్రాలు",
    process_flow: "ప్రాసెస్ ఫ్లో",
    // Quality translations
    quality_management: "నాణ్యత నిర్వహణ",
    quality_overview_description: "దారం నాణ్యత పారామితులను పర్యవేక్షించండి మరియు విశ్లేషించండి",
    real_time_analysis: "రియల్-టైమ్ విశ్లేషణ",
    quality_trends: "నాణ్యత ధోరణులు",
    quality_alerts: "నాణ్యత హెచ్చరికలు",
    yarn_parameters: "దారం పారామితులు",
    add_test: "పరీక్ష జోడించండి",
    test_results: "పరీక్ష ఫలితాలు",
    parameters: "పారామితులు",
    twist: "మలుపు",
    evenness: "సమతుల్యత",
    tensile_strength: "లాగుట బలం",
    elongation: "పొడిగింపు",
    hairiness: "రోమము",
    last_7_days: "గత 7 రోజులు",
    deviation_detected: "వ్యత్యాసం గుర్తించబడింది",
    critical_alert: "క్రిటికల్ అలర్ట్",
    warning_alert: "హెచ్చరిక అలర్ట్",
    info_alert: "సమాచారం",
    quality_forecast: "నాణ్యత ఫోర్కాస్ట్",
    recommendations: "సిఫార్సులు",
    corrective_actions: "సరిదిద్దే చర్యలు",
    sensor_data: "సెన్సార్ డేటా",
    vision_systems: "విజన్ సిస్టమ్స్",
    machine_learning: "మెషిన్ లెర్నింగ్",
    predicted_issues: "ముందుగా అంచనా వేసిన సమస్యలు",
    compliance: "అనుసరణ",
    standards: "ప్రమాణాలు",
    // Inventory translations
    inventory_management: "ఇన్వెంటరీ మేనేజ్మెంట్",
    inventory_overview_description: "స్పిన్నింగ్ మిల్ ఇన్వెంటరీని ట్రాక్ చేయండి మరియు నిర్వహించండి",
    raw_materials: "ముడి పదార్థాలు",
    work_in_progress: "పని పురోగతిలో ఉంది",
    finished_goods: "ముగించిన వస్తువులు",
    inventory_analytics: "ఇన్వెంటరీ అనలిటిక్స్",
    scan_barcode: "బార్కోడ్‌ని స్కాన్ చేయండి",
    add_item: "ఐటెమ్‌ని జోడించండి",
    item_name: "వస్తువు పేరు",
    item_code: "వస్తువు కోడ్",
    category: "వర్గం",
    quantity: "పరిమాణం",
    unit: "యూనిట్",
    location: "స్థానం",
    status: "స్థితి",
    last_updated: "చివరిగా నవీకరించబడింది",
    reorder_level: "రీఆర్డర్ లెవెల్",
    reorder_alerts: "రీఆర్డర్ అలర్ట్స్",
    low_stock: "తక్కువ స్టాక్",
    out_of_stock: "స్టాక్ లేదు",
    expiring_soon: "త్వరలో గడువు ముగుస్తోంది",
    days_until_reorder: "రీఆర్డర్ వరకు రోజులు",
    inventory_value: "ఇన్వెంటరీ విలువ",
    turnover_rate: "టర్నోవర్ రేట్",
    wastage: "వృధా",
    in_stock: "స్టాక్‌లో ఉంది",
    cotton: "పత్తి",
    polyester: "పాలిస్టర్",
    viscose: "విస్కోస్",
    yarn_packages: "దారం ప్యాకేజీలు",
    tons: "టన్నులు",
    kilograms: "కిలోగ్రాములు",
    units: "యూనిట్లు",
  },
  hindi: {
    dashboard: "डैशबोर्ड",
    production: "उत्पादन",
    inventory: "इन्वेंटरी",
    quality: "गुणवत्ता",
    finance: "वित्त",
    hr: "मानव संसाधन",
    crm: "ग्राहक संबंध",
    settings: "सेटिंग्स",
    language: "भाषा",
    welcome: "SpinWise ERP में आपका स्वागत है",
    overview: "सिस्टम अवलोकन",
    pendingOrders: "अपूर्ण आदेश",
    stockStatus: "स्टॉक स्थिति",
    qualityMetrics: "गुणवत्ता मेट्रिक्स",
    recentTransactions: "हाल के लेनदेन",
    employeePerformance: "कर्मचारी प्रदर्शन",
    customerOrders: "ग्राहक आदेश",
    rawMaterials: "कच्चा माल",
    workInProgress: "कार्य प्रगति पर है",
    finishedGoods: "तैयार माल",
    chat: "सहायक के साथ चैट करें",
    chatPlaceholder: "यार्न, मशीनों या प्रक्रियाओं के बारे में पूछें...",
    logout: "लॉगआउट",
    // Production translations
    running_machines: "चालू मशीनें",
    issues: "समस्याएं",
    avg_efficiency: "औसत दक्षता",
    daily_production: "दैनिक उत्पादन",
    of_total: "कुल का",
    warnings: "चेतावनियां",
    errors: "त्रुटियां",
    from_yesterday: "कल से",
    production_metrics: "उत्पादन मेट्रिक्स",
    last_24_hours: "पिछले 24 घंटे",
    quality_indicators: "गुणवत्ता संकेतक",
    current_shift: "वर्तमान शिफ्ट",
    yarn_strength: "यार्न की मजबूती",
    yarn_evenness: "यार्न की समानता",
    imperfections: "दोष",
    waste_percentage: "अपशिष्ट प्रतिशत",
    good: "अच्छा",
    average: "औसत",
    poor: "खराब",
    machine_status: "मशीन की स्थिति",
    production_kg: "उत्पादन (किलोग्राम)",
    quality_percent: "गुणवत्ता (%)",
    efficiency_percent: "दक्षता (%)",
    production_management: "उत्पादन प्रबंधन",
    production_overview_description: "स्पिनिंग मिल उत्पादन प्रक्रियाओं की निगरानी और प्रबंधन करें",
    add_machine: "मशीन जोड़ें",
    machines: "मशीनें",
    process_flow: "प्रक्रिया प्रवाह",
    // Quality translations
    quality_management: "गुणवत्ता प्रबंधन",
    quality_overview_description: "यार्न गुणवत्ता पैरामीटर की निगरानी और विश्लेषण करें",
    real_time_analysis: "वास्तविक समय विश्लेषण",
    quality_trends: "गुणवत्ता रुझान",
    quality_alerts: "गुणवत्ता अलर्ट",
    yarn_parameters: "यार्न पैरामीटर",
    add_test: "परीक्षण जोड़ें",
    test_results: "परीक्षण परिणाम",
    parameters: "पैरामीटर",
    twist: "मोड़",
    evenness: "समता",
    tensile_strength: "तन्य शक्ति",
    elongation: "विस्तार",
    hairiness: "रोएंदारपन",
    last_7_days: "पिछले 7 दिन",
    deviation_detected: "विचलन का पता चला",
    critical_alert: "महत्वपूर्ण अलर्ट",
    warning_alert: "चेतावनी अलर्ट",
    info_alert: "जानकारी",
    quality_forecast: "गुणवत्ता पूर्वानुमान",
    recommendations: "सिफारिशें",
    corrective_actions: "सुधारात्मक कार्रवाई",
    sensor_data: "सेंसर डेटा",
    vision_systems: "विज़न सिस्टम",
    machine_learning: "मशीन लर्निंग",
    predicted_issues: "अनुमानित समस्याएं",
    compliance: "अनुपालन",
    standards: "मानक",
    // Inventory translations
    inventory_management: "इन्वेंटरी प्रबंधन",
    inventory_overview_description: "स्पिनिंग मिल इन्वेंटरी को ट्रैक और प्रबंधित करें",
    raw_materials: "कच्चा माल",
    work_in_progress: "प्रगति पर कार्य",
    finished_goods: "तैयार माल",
    inventory_analytics: "इन्वेंटरी एनालिटिक्स",
    scan_barcode: "बारकोड स्कैन करें",
    add_item: "आइटम जोड़ें",
    item_name: "आइटम नाम",
    item_code: "आइटम कोड",
    category: "श्रेणी",
    quantity: "मात्रा",
    unit: "इकाई",
    location: "स्थान",
    status: "स्थिति",
    last_updated: "अंतिम अपडेट",
    reorder_level: "पुनः आदेश स्तर",
    reorder_alerts: "पुनः आदेश अलर्ट",
    low_stock: "कम स्टॉक",
    out_of_stock: "स्टॉक ख़त्म",
    expiring_soon: "जल्द समाप्त होने वाला",
    days_until_reorder: "पुनः आदेश तक दिन",
    inventory_value: "इन्वेंटरी मूल्य",
    turnover_rate: "टर्नओवर दर",
    wastage: "अपशिष्ट",
    in_stock: "स्टॉक में",
    cotton: "कपास",
    polyester: "पॉलिएस्टर",
    viscose: "विस्कोस",
    yarn_packages: "यार्न पैकेज",
    tons: "टन",
    kilograms: "किलोग्राम",
    units: "इकाइयां",
  },
  kannada: {
    dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    production: "ಉತ್ಪಾದನೆ",
    inventory: "ಸರಕುಪಟ್ಟಿ",
    quality: "ಗುಣಮಟ್ಟ",
    finance: "ಹಣಕಾಸು",
    hr: "ಮಾನವ ಸಂಪನ್ಮೂಲಗಳು",
    crm: "ಗ್ರಾಹಕ ಸಂಬಂಧಗಳು",
    settings: "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
    language: "ಭಾಷೆ",
    welcome: "SpinWise ERP ಗೆ ಸುಸ್ವಾಗತ",
    overview: "ಸಿಸ್ಟಮ್ ಅವಲೋಕನ",
    pendingOrders: "ಬಾಕಿ ಇರುವ ಆರ್ಡರ್‌ಗಳು",
    stockStatus: "ಸ್ಟಾಕ್ ಸ್ಥಿತಿ",
    qualityMetrics: "ಗುಣಮಟ್ಟದ ಮೆಟ್ರಿಕ್ಸ್",
    recentTransactions: "ಇತ್ತೀಚಿನ ವಹಿವಾಟುಗಳು",
    employeePerformance: "ನೌಕರರ ಕಾರ್ಯಕ್ಷಮತೆ",
    customerOrders: "ಗ್ರಾಹಕರ ಆರ್ಡರ್‌ಗಳು",
    rawMaterials: "ಕಚ್ಚಾ ವಸ್ತುಗಳು",
    workInProgress: "ಕಾರ್ಯ ಪ್ರಗತಿಯಲ್ಲಿದೆ",
    finishedGoods: "ಪೂರ್ಣಗೊಂಡ ಸರಕುಗಳು",
    chat: "ಸಹಾಯಕರೊಂದಿಗೆ ಚಾಟ್ ಮಾಡಿ",
    chatPlaceholder: "ನೂಲು, ಯಂತ್ರಗಳು ಅಥವಾ ಕಾರ್ಯವಿಧಾನಗಳ ಬಗ್ಗೆ ಕೇಳಿ...",
    logout: "ಲಾಗ್ ಔಟ್",
    // Production translations
    running_machines: "ಚಾಲನೆಯಲ್ಲಿರುವ ಯಂತ್ರಗಳು",
    issues: "ಸಮಸ್ಯೆಗಳು",
    avg_efficiency: "ಸರಾಸರಿ ದಕ್ಷತೆ",
    daily_production: "ದೈನಂದಿನ ಉತ್ಪಾದನೆ",
    of_total: "ಒಟ್ಟಿನದ್ದು",
    warnings: "ಎಚ್ಚರಿಕೆಗಳು",
    errors: "ದೋಷಗಳು",
    from_yesterday: "ನಿನ್ನೆಯಿಂದ",
    production_metrics: "ಉತ್ಪಾದನಾ ಮೆಟ್ರಿಕ್ಸ್",
    last_24_hours: "ಕಳೆದ 24 ಗಂಟೆಗಳು",
    quality_indicators: "ಗುಣಮಟ್ಟದ ಸೂಚಕಗಳು",
    current_shift: "ಪ್ರಸ್ತುತ ಶಿಫ್ಟ್",
    yarn_strength: "ನೂಲಿನ ಶಕ್ತಿ",
    yarn_evenness: "ನೂಲಿನ ಏಕರೂಪತೆ",
    imperfections: "ದೋಷಗಳು",
    waste_percentage: "ತ್ಯಾಜ್ಯ ಶೇಕಡಾವಾರು",
    good: "ಉತ್ತಮ",
    average: "ಸರಾಸರಿ",
    poor: "ಕಳಪೆ",
    machine_status: "ಯಂತ್ರದ ಸ್ಥಿತಿ",
    production_kg: "ಉತ್ಪಾದನೆ (ಕೆಜಿ)",
    quality_percent: "ಗುಣಮಟ್ಟ (%)",
    efficiency_percent: "ದಕ್ಷತೆ (%)",
    production_management: "ಉತ್ಪಾದನಾ ನಿರ್ವಹಣೆ",
    production_overview_description: "ಸ್ಪಿನ್ನಿಂಗ್ ಮಿಲ್ ಉತ್ಪಾದನಾ ಪ್ರಕ್ರಿಯೆಗಳನ್ನು ಮೇಲ್ವಿಚಾರಣೆ ಮಾಡಿ ಮತ್ತು ನಿರ್ವಹಿಸಿ",
    add_machine: "ಯಂತ್ರವನ್ನು ಸೇರಿಸಿ",
    machines: "ಯಂತ್ರಗಳು",
    process_flow: "ಪ್ರಕ್ರಿಯೆ ಹರಿವು",
    // Quality translations
    quality_management: "ಗುಣಮಟ್ಟ ನಿರ್ವಹಣೆ",
    quality_overview_description: "ನೂಲಿನ ಗುಣಮಟ್ಟದ ಪ್ಯಾರಾಮೀಟರ್‌ಗಳನ್ನು ಮೇಲ್ವಿಚಾರಣೆ ಮಾಡಿ ಮತ್ತು ವಿಶ್ಲೇಷಿಸಿ",
    real_time_analysis: "ನೈಜ-ಸಮಯದ ವಿಶ್ಲೇಷಣೆ",
    quality_trends: "ಗುಣಮಟ್ಟದ ಪ್ರವೃತ್ತಿಗಳು",
    quality_alerts: "ಗುಣಮಟ್ಟದ ಎಚ್ಚರಿಕೆಗಳು",
    yarn_parameters: "ನೂಲಿನ ಪ್ಯಾರಾಮೀಟರ್‌ಗಳು",
    add_test: "ಪರೀಕ್ಷೆಯನ್ನು ಸೇರಿಸಿ",
    test_results: "ಪರೀಕ್ಷಾ ಫಲಿತಾಂಶಗಳು",
    parameters: "ಪ್ಯಾರಾಮೀಟರ್‌ಗಳು",
    twist: "ತಿರುವು",
    evenness: "ಏಕರೂಪತೆ",
    tensile_strength: "ಎಳೆತದ ಶಕ್ತಿ",
    elongation: "ವಿಸ್ತರಣೆ",
    hairiness: "ಕೂದಲಿನಂತೆ",
    last_7_days: "ಕಳೆದ 7 ದಿನಗಳು",
    deviation_detected: "ವಿಚಲನೆಯನ್ನು ಪತ್ತೆಮಾಡಲಾಗಿದೆ",
    critical_alert: "ಗಂಭೀರ ಎಚ್ಚರಿಕೆ",
    warning_alert: "ಎಚ್ಚರಿಕೆ ಅಲರ್ಟ್",
    info_alert: "ಮಾಹಿತಿ",
    quality_forecast: "ಗುಣಮಟ್ಟದ ಮುನ್ಸೂಚನೆ",
    recommendations: "ಶಿಫಾರಸುಗಳು",
    corrective_actions: "ಸರಿಪಡಿಸುವ ಕ್ರಮಗಳು",
    sensor_data: "ಸೆನ್ಸರ್ ಡೇಟಾ",
    vision_systems: "ದೃಷ್ಟಿ ವ್ಯವಸ್ಥೆಗಳು",
    machine_learning: "ಮಷೀನ್ ಲರ್ನಿಂಗ್",
    predicted_issues: "ಮುನ್ಸೂಚಿತ ಸಮಸ್ಯೆಗಳು",
    compliance: "ಅನುಸರಣೆ",
    standards: "ಮಾನದಂಡಗಳು",
    // Inventory translations
    inventory_management: "ಸರಕು ನಿರ್ವಹಣೆ",
    inventory_overview_description: "ಸ್ಪಿನ್ನಿಂಗ್ ಮಿಲ್ ಸರಕುಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ ಮತ್ತು ನಿರ್ವಹಿಸಿ",
    raw_materials: "ಕಚ್ಚಾ ವಸ್ತುಗಳು",
    work_in_progress: "ಪ್ರಗತಿಯಲ್ಲಿರುವ ಕೆಲಸ",
    finished_goods: "ಮುಗಿದ ಸರಕುಗಳು",
    inventory_analytics: "ಸರಕು ವಿಶ್ಲೇಷಣೆಗಳು",
    scan_barcode: "ಬಾರ್‌ಕೋಡ್ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ",
    add_item: "ವಸ್ತುವನ್ನು ಸೇರಿಸಿ",
    item_name: "ವಸ್ತುವಿನ ಹೆಸರು",
    item_code: "ವಸ್ತುವಿನ ಕೋಡ್",
    category: "ವರ್ಗ",
    quantity: "ಪ್ರಮಾಣ",
    unit: "ಘಟಕ",
    location: "ಸ್ಥಳ",
    status: "ಸ್ಥಿತಿ",
    last_updated: "ಕೊನೆಯದಾಗಿ ನವೀಕರಿಸಲಾಗಿದೆ",
    reorder_level: "ಮರುಆದೇಶ ಮಟ್ಟ",
    reorder_alerts: "ಮರುಆದೇಶ ಎಚ್ಚರಿಕೆಗಳು",
    low_stock: "ಕಡಿಮೆ ಸ್ಟಾಕ್",
    out_of_stock: "ಸ್ಟಾಕ್ ಖಾಲಿ",
    expiring_soon: "ಶೀಘ್ರದಲ್ಲೇ ಅವಧಿ ಮುಗಿಯುತ್ತಿದೆ",
    days_until_reorder: "ಮರುಆದೇಶದವರೆಗೆ ದಿನಗಳು",
    inventory_value: "ಸರಕಿನ ಮೌಲ್ಯ",
    turnover_rate: "ಟರ್ನ್ಓವರ್ ದರ",
    wastage: "ಅಪವ್ಯಯ",
    in_stock: "ಸ್ಟಾಕ್‌ನಲ್ಲಿದೆ",
    cotton: "ಹತ್ತಿ",
    polyester: "ಪಾಲಿಎಸ್ಟರ್",
    viscose: "ವಿಸ್ಕೋಸ್",
    yarn_packages: "ನೂಲು ಪ್ಯಾಕೇಜುಗಳು",
    tons: "ಟನ್‌ಗಳು",
    kilograms: "ಕಿಲೋಗ್ರಾಂಗಳು",
    units: "ಘಟಕಗಳು",
  },
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const savedLanguage = localStorage.getItem("spinwise-language");
    return (savedLanguage as Language) || "english";
  });

  useEffect(() => {
    localStorage.setItem("spinwise-language", language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
