// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vasemcizlnnjsmonyvfg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZhc2VtY2l6bG5uanNtb255dmZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwNDY1NTIsImV4cCI6MjA1NzYyMjU1Mn0.U6UgpOi78J69EndeoBDqGQgjOQQS4Tp-cNduSyl6Yj8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);